### ISSUE TITLE
Unsupported callback API version

### ISSUE THREAD

**Issue by MrMSch** [richibrics/IoTuring#97]
After installing 2024.1.1, PIP installed Paho 2.0 which includes breaking changes, which you can see here: https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html

```
[ 2024-02-19 00:15:37 |   Info   |              App              ]  Name: IoTuring
[ 2024-02-19 00:15:37 |   Info   |              App              ]  Version: 2024.1.1
[ 2024-02-19 00:15:37 |   Info   |              App              ]  Description: Simple and powerful cross-platform script to control your pc and share statistics
                                                                    using communication protocols like MQTT and home control hubs like HomeAssistant.
[ 2024-02-19 00:15:37 |   Info   |          Configurator         ]  Run the script with -c to enter configuration mode
[ 2024-02-19 00:15:37 |   Info   |         Entity.AppInfo        ]  Initialization successfully completed
[ 2024-02-19 00:15:37 |   Info   |         Entity.Battery        ]  Initialization successfully completed
[ 2024-02-19 00:15:37 |   Info   |           Entity.Cpu          ]  Initialization successfully completed
[ 2024-02-19 00:15:37 |   Info   |           Entity.Ram          ]  Initialization successfully completed
[ 2024-02-19 00:15:37 |   Info   |          Entity.Power         ]  Initialization successfully completed
[ 2024-02-19 00:15:37 |   Info   |              MQTT             ]  Preparing MQTT client
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Lib\site-packages\IoTuring\__main__.py", line 6, in <module>
    loop()
  File "C:\Program Files\Python312\Lib\site-packages\IoTuring\__init__.py", line 93, in loop
    warehouse.Start()
  File "C:\Program Files\Python312\Lib\site-packages\IoTuring\ClassManager\..\Warehouse\Deployments\HomeAssistantWarehouse\HomeAssistantWarehouse.py", line 338, in Start
    self.client = MQTTClient(self.GetFromConfigurations(CONFIG_KEY_ADDRESS),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\IoTuring\Protocols\MQTTClient\MQTTClient.py", line 38, in __init__
    self.SetupClient()
  File "C:\Program Files\Python312\Lib\site-packages\IoTuring\Protocols\MQTTClient\MQTTClient.py", line 45, in SetupClient
    self.client = MqttClient.Client(self.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\paho\mqtt\client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
```

**Comment by MrMSch** [comment]
I updated line 45 of MQTTClient.py to the following and it works.  This is a stop gap however as v2 should really be adopted instead.

```
self.client = MqttClient.Client(MqttClient.CallbackAPIVersion.VERSION1, self.name)
```

**Comment by richibrics** [comment]
Thanks, we will address this issue soon 👍
